export const DEFAULT_CAR_SPECS = [
  {
    title: 'Безпека',
    items: [
      { label: 'Антиблокувальна система (ABS)', value: false },
      { label: 'Антипробуксовочна система (ASR)', value: false },
      { label: 'Блокування замків задніх дверей', value: false },
      { label: 'Датчик тиску в шинах', value: false },
      { label: 'Допомога при спуску', value: false },
      { label: 'Допомога при старті в гору', value: false },
      { label: 'Імобілайзер', value: false },
      { label: 'Запобігання зіткнення', value: false },
      { label: 'Контроль за смугами руху', value: false },
      { label: 'Контроль сліпих зон', value: false },
      { label: 'Сигналізація', value: false },
      { label: 'Розпізнавання дорожніх знаків', value: false },
      { label: 'Система стабілізації (ESP)', value: false },
      { label: 'Центральний замок', value: false },
    ],
  },

  {
    title: 'Комфорт і обладнання',
    items: [
      { label: 'Адаптивний круїз', value: false },
      { label: 'Бардачок з охолодженням', value: false },
      { label: 'Бездротова зарядка для смартфону', value: false },
      { label: 'Бортовий комп’ютер', value: false },
      { label: 'Відкриття багажника без допомоги рук', value: false },
      { label: 'Датчик дощу', value: false },
      { label: 'Декоративне підсвічування салону', value: false },
      { label: 'Дистанційний запуск двигуна', value: false },
      { label: 'Доводчик дверей', value: false },
      { label: 'Електронна приладова панель', value: false },
      { label: 'Електро привід дзеркал', value: false },
      { label: 'Електропривід кришки багажника', value: false },
      { label: 'Електроскладання дзеркал', value: false },
      { label: 'Запуск двигуна з кнопки', value: false },
      { label: 'Круїз контроль', value: false },
      { label: 'Люк', value: false },
      { label: 'Мультифункціональне кермо', value: false },
      { label: 'Обігрів керма', value: false },
      { label: 'Обігрів лобового скла', value: false },
      { label: 'Оздоблення керма шкірою', value: false },
      { label: 'Оздоблення стелі чорного кольору', value: false },
      { label: 'Оздоблення шкірою важеля КПП', value: false },
      { label: 'Панорамний дах', value: false },
      { label: 'Підігрів дзеркал', value: false },
      { label: 'Підрульові пелюстки перемикання передач', value: false },
      { label: 'Проекційний дисплей', value: false },
      { label: 'Розетка 12V', value: false },
      { label: 'Розетка 220V', value: false },
      { label: 'Сидіння з масажем', value: false },
      { label: 'Система "Старт-стоп"', value: false },
      { label: 'Система доступу без ключа', value: false },
      { label: 'Сонцезахисна шторка на задньому склі', value: false },
      { label: 'Сонцезахисна шторка на задніх дверях', value: false },
      { label: 'Тоновані вікна', value: false },
      { label: 'Третій ряд сидінь', value: false },
      { label: 'Холодильник', value: false },
      { label: 'Кондиціонер', value: false },
      { label: 'Клімат-контроль 1-зонний', value: false },
      { label: 'Клімат-контроль 2-зонний', value: false },
      { label: 'Клімат-контроль багатозонний', value: false },
      { label: 'Автономний обігрівач Webasto', value: false },
      { label: 'Пневмопідвіска', value: false },
      { label: 'Захист картера', value: false },
      { label: 'Фаркоп', value: false },
      { label: 'Підігрів передніх сидінь', value: false },
      { label: 'Підігрів передніх та задніх сидінь', value: false },
      { label: 'Пам’ять сидінь', value: false },
      { label: 'Задня камера', value: false },
      { label: 'Камера 360', value: false },
      { label: 'Парктронік задній', value: false },
      { label: 'Парктронік передній', value: false },
      { label: 'Передня камера', value: false },
      { label: 'Система автоматичного паркування', value: false },
    ],
  },

  {
    title: 'Мультимедіа',
    items: [
      { label: 'Android Auto', value: false },
      { label: 'CarPlay', value: false },
      { label: 'AUX', value: false },
      { label: 'Bluetooth', value: false },
      { label: 'MirrorLink', value: false },
      { label: 'USB', value: false },
      { label: 'Голосове керування', value: false },
      { label: 'Мультимедійна система з LCD-екраном', value: false },
      { label: 'Навігаційна система', value: false },
      { label: 'Система мультимедіа для задніх пасажирів', value: false },
    ],
  },

  {
    title: 'Світло',
    items: [
      { label: 'Ксенонові / Біксенонові', value: false },
      { label: 'Лазерні', value: false },
      { label: 'Світлодіоди', value: false },
      { label: 'Матричні', value: false },
      { label: 'Галогенні', value: false },
      { label: 'Датчик світла', value: false },
      { label: 'Денні ходові вогні', value: false },
      { label: 'Омивач фар', value: false },
      { label: 'Протитуманні фари', value: false },
      { label: 'Система адаптивного освітлення', value: false },
      { label: 'Система управління дальнім світлом', value: false },
    ],
  },

  {
    title: "Інтер'єр",
    items: [
      { label: 'Салон з тканини', value: false },
      { label: 'Салон зі шкіри', value: false },
      { label: 'Салон комбінований', value: false },
      { label: 'Салон зі штучної шкіри', value: false },
      { label: 'Салон з алькантара', value: false },
    ],
  },

  {
    title: "Екстер'єр",
    items: [
      { label: 'Сталеві диски', value: false },
      { label: 'Литі диски', value: false },
      { label: 'Тимчасове запасне колесо', value: false },
      { label: 'Запасне колесо', value: false },
      { label: 'Двокольорове фарбування елементів кузова', value: false },
      { label: 'Рейлінги на даху', value: false },
    ],
  },
];
