export const carsMock = [
  {
    id: 1,
    carBrand: 'HAVAL',
    model: 'H5',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Луцьк',
    dealerSity: 'м. Луцьк',
    engine: '2.0 D',
    year: '2025',
    exteriorColor: 'CX Purple',
    regularPrice: '1 595 000',
    loanRepayment: '9600',
    specialOffer: false,
    pickUpOffer: true,
    availablCar: true,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    transmission: 'Автомат',
  },
  {
    id: 2,
    carBrand: 'HAVAL',
    model: 'JOLION',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Київ',
    dealerSity: 'м. Київ',
    engine: '1.5 T',
    year: '2024',
    exteriorColor: 'White Pearl',
    regularPrice: '1 250 000',
    loanRepayment: '8200',
    specialOffer: true,
    pickUpOffer: true,
    availablCar: true,
    trimLevel: 'Luxury',
    fuelType: 'Дизель',
    transmission: 'Автомат',
  },
  {
    id: 3,
    carBrand: 'HAVAL',
    model: 'DARGO',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Львів',
    dealerSity: 'м. Львів',
    engine: '2.0 T',
    year: '2025',
    exteriorColor: 'Black',
    regularPrice: '1 720 000',
    loanRepayment: '10200',
    specialOffer: false,
    pickUpOffer: false,
    availablCar: false,
    trimLevel: 'Standart',
    fuelType: 'Електро',
    transmission: 'Механіка',
  },
  {
    id: 4,
    carBrand: 'HAVAL',
    model: 'H6',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Рівне',
    dealerSity: 'м. Рівне',
    engine: '2.0 T',
    year: '2024',
    exteriorColor: 'Silver',
    regularPrice: '1 480 000',
    loanRepayment: '8900',
    specialOffer: true,
    pickUpOffer: false,
    availablCar: true,
    trimLevel: 'Luxury',
    fuelType: 'Гібрид',
    transmission: 'Робот',
  },
  {
    id: 5,
    carBrand: 'HAVAL',
    model: 'M6',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Тернопіль',
    dealerSity: 'м. Тернопіль',
    engine: '1.5 T',
    year: '2023',
    exteriorColor: 'Red',
    regularPrice: '1 050 000',
    loanRepayment: '7100',
    specialOffer: true,
    pickUpOffer: true,
    availablCar: false,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    transmission: 'Автомат',
  },
  {
    id: 6,
    carBrand: 'HAVAL',
    model: 'H2',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Харків',
    dealerSity: 'м. Харків',
    engine: '1.5 T',
    year: '2023',
    exteriorColor: 'Blue',
    regularPrice: '990 000',
    loanRepayment: '6800',
    specialOffer: false,
    pickUpOffer: true,
    availablCar: true,
    trimLevel: 'Luxury',
    fuelType: 'Бензин',
    transmission: 'Автомат',
  },
  {
    id: 7,
    carBrand: 'HAVAL',
    model: 'F7',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Одеса',
    dealerSity: 'м. Одеса',
    engine: '2.0 T',
    year: '2024',
    exteriorColor: 'Grey',
    regularPrice: '1 430 000',
    loanRepayment: '8700',
    specialOffer: true,
    pickUpOffer: false,
    availablCar: true,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    transmission: 'Автомат',
  },
  {
    id: 8,
    carBrand: 'HAVAL',
    model: 'F7x',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Дніпро',
    dealerSity: 'м. Дніпро',
    engine: '2.0 T',
    year: '2025',
    exteriorColor: 'Dark Green',
    regularPrice: '1 610 000',
    loanRepayment: '9900',
    specialOffer: false,
    pickUpOffer: true,
    availablCar: false,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    transmission: 'Автомат',
  },
  {
    id: 9,
    carBrand: 'HAVAL',
    model: 'H9',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Запоріжжя',
    dealerSity: 'м. Запоріжжя',
    engine: '2.0 D',
    year: '2025',
    exteriorColor: 'White',
    regularPrice: '1 980 000',
    loanRepayment: '11500',
    specialOffer: true,
    pickUpOffer: false,
    availablCar: true,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    transmission: 'Автомат',
  },
  {
    id: 10,
    carBrand: 'HAVAL',
    model: 'H6 GT',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    bealerName: 'Богдан-Авто Чернівці',
    dealerSity: 'м. Чернівці',
    engine: '2.0 T',
    year: '2025',
    exteriorColor: 'Orange',
    regularPrice: '1 670 000',
    loanRepayment: '10100',
    specialOffer: true,
    pickUpOffer: true,
    availablCar: true,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    transmission: 'Автомат',
  },
];
