export const carsMock = [
  {
    id: 1,
    carBrand: 'HAVAL',
    model: 'H5',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img5.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img1.jpg',
    ],
    bealerName: 'Богдан-Авто Луцьк',
    dealerSity: 'м. Луцьк',
    engine: '2.0 D',
    enginePowerHP: null,
    year: '2025',
    exteriorColor: 'CX Purple',
    regularPrice: '1 595 000',
    loanRepayment: '9600',
    specialOffer: false,
    pickUpOffer: true,
    availablCar: true,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    accel0to100: 'Н/Д',
    maximumSpeed: '200',
    transmission: 'Автомат',
    cityFuelConsumption: '7.5',
    highwayFuelConsumption: '5.1',
    fuelTankCapacity: '78',
    driveType: 'Передній',
    combinedFuelConsumption: '6.2',
    lengthMm: '4510',
    widthMm: '1820',
    heightMm: '1720',
    wheelbaseMm: '2710',
    curbWeightKg: '1550',
    grossWeightKg: '2050',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: false },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },
  {
    id: 2,
    carBrand: 'HAVAL',
    model: 'JOLION',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-2-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-2-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/jolion/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/jolion/img3.jpg',
    ],
    bealerName: 'Богдан-Авто Київ',
    dealerSity: 'м. Київ',
    engine: '1.5 T',
    enginePowerHP: '150/3600',
    year: '2024',
    exteriorColor: 'White Pearl',
    regularPrice: '1 250 000',
    loanRepayment: '8200',
    specialOffer: true,
    pickUpOffer: true,
    availablCar: true,
    trimLevel: 'Luxury',
    fuelType: 'Дизель',
    accel0to100: '20',
    maximumSpeed: '200',
    transmission: 'Автомат',
    cityFuelConsumption: '7.5',
    highwayFuelConsumption: '5.1',
    fuelTankCapacity: '56',
    driveType: 'Задній',
    combinedFuelConsumption: '6.2',
    lengthMm: '4470',
    widthMm: '1820',
    heightMm: '1680',
    wheelbaseMm: '2700',
    curbWeightKg: '1450',
    grossWeightKg: '2000',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: true },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },
  {
    id: 3,
    carBrand: 'HAVAL',
    model: 'DARGO',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img5.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img1.jpg',
    ],
    bealerName: 'Богдан-Авто Львів',
    dealerSity: 'м. Львів',
    engine: '2.0 T',
    enginePowerHP: '150/3600',
    year: '2025',
    exteriorColor: 'Black',
    regularPrice: '1 720 000',
    loanRepayment: '10200',
    specialOffer: false,
    pickUpOffer: false,
    availablCar: false,
    trimLevel: 'Standart',
    fuelType: 'Електро',
    accel0to100: 'Н/Д',
    maximumSpeed: '200',
    transmission: 'Механіка',
    cityFuelConsumption: '8.5',
    highwayFuelConsumption: '4.1',
    fuelTankCapacity: '79',
    driveType: 'Передній',
    combinedFuelConsumption: '6.2',
    lengthMm: '4520',
    widthMm: '1840',
    heightMm: '1725',
    wheelbaseMm: '2725',
    curbWeightKg: '1580',
    grossWeightKg: '2070',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: true },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },

  {
    id: 4,
    carBrand: 'HAVAL',
    model: 'H6',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img5.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img1.jpg',
    ],
    bealerName: 'Богдан-Авто Рівне',
    dealerSity: 'м. Рівне',
    engine: '2.0 T',
    enginePowerHP: '150/3600',
    year: '2024',
    exteriorColor: 'Silver',
    regularPrice: '1 480 000',
    loanRepayment: '8900',
    specialOffer: true,
    pickUpOffer: false,
    availablCar: true,
    trimLevel: 'Luxury',
    fuelType: 'Гібрид',
    accel0to100: '30',
    maximumSpeed: '200',
    transmission: 'Робот',
    cityFuelConsumption: '7.5',
    highwayFuelConsumption: '5.1',
    fuelTankCapacity: '54',
    driveType: 'Передній',
    combinedFuelConsumption: '3.4',
    lengthMm: '4500',
    widthMm: '1825',
    heightMm: '1720',
    wheelbaseMm: '2710',
    curbWeightKg: '1560',
    grossWeightKg: '2050',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: true },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },
  {
    id: 5,
    carBrand: 'HAVAL',
    model: 'M6',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img5.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img1.jpg',
    ],
    bealerName: 'Богдан-Авто Тернопіль',
    dealerSity: 'м. Тернопіль',
    engine: '1.5 T',
    enginePowerHP: '150/3600',
    year: '2023',
    exteriorColor: 'Red',
    regularPrice: '1 050 000',
    loanRepayment: '7100',
    specialOffer: true,
    pickUpOffer: true,
    availablCar: false,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    accel0to100: 'Н/Д',
    maximumSpeed: '200',
    transmission: 'Автомат',
    cityFuelConsumption: '7.5',
    highwayFuelConsumption: '5.1',
    fuelTankCapacity: '64',
    driveType: 'Задній',
    combinedFuelConsumption: '6.2',
    lengthMm: '4480',
    widthMm: '1815',
    heightMm: '1705',
    wheelbaseMm: '2705',
    curbWeightKg: '1470',
    grossWeightKg: '2020',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: true },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },
  {
    id: 6,
    carBrand: 'HAVAL',
    model: 'H2',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img5.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img1.jpg',
    ],
    bealerName: 'Богдан-Авто Харків',
    dealerSity: 'м. Харків',
    engine: '1.5 T',
    enginePowerHP: '150/3600',
    year: '2023',
    exteriorColor: 'Blue',
    regularPrice: '990 000',
    loanRepayment: '6800',
    specialOffer: false,
    pickUpOffer: true,
    availablCar: true,
    trimLevel: 'Luxury',
    fuelType: 'Бензин',
    accel0to100: 'Н/Д',
    maximumSpeed: '200',
    transmission: 'Автомат',
    cityFuelConsumption: '7.5',
    highwayFuelConsumption: '5.1',
    fuelTankCapacity: '78',
    driveType: 'Повний',
    combinedFuelConsumption: '6.2',
    lengthMm: '4475',
    widthMm: '1810',
    heightMm: '1735',
    wheelbaseMm: '2700',
    curbWeightKg: '1500',
    grossWeightKg: '2050',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: true },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },
  {
    id: 7,
    carBrand: 'HAVAL',
    model: 'F7',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img5.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img1.jpg',
    ],
    bealerName: 'Богдан-Авто Одеса',
    dealerSity: 'м. Одеса',
    engine: '2.0 T',
    enginePowerHP: '150/3600',
    year: '2024',
    exteriorColor: 'Grey',
    regularPrice: '1 430 000',
    loanRepayment: '8700',
    specialOffer: true,
    pickUpOffer: false,
    availablCar: true,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    accel0to100: 'Н/Д',
    maximumSpeed: '200',
    transmission: 'Автомат',
    cityFuelConsumption: '7.5',
    highwayFuelConsumption: '5.1',
    fuelTankCapacity: '78',
    driveType: 'Повний',
    combinedFuelConsumption: '6.2',
    lengthMm: '4590',
    widthMm: '1870',
    heightMm: '1725',
    wheelbaseMm: '2725',
    curbWeightKg: '1600',
    grossWeightKg: '2100',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: true },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },
  {
    id: 8,
    carBrand: 'HAVAL',
    model: 'F7x',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img5.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img1.jpg',
    ],
    bealerName: 'Богдан-Авто Дніпро',
    dealerSity: 'м. Дніпро',
    engine: '2.0 T',
    enginePowerHP: '150/3600',
    year: '2025',
    exteriorColor: 'Dark Green',
    regularPrice: '1 610 000',
    loanRepayment: '9900',
    specialOffer: false,
    pickUpOffer: true,
    availablCar: false,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    accel0to100: 'Н/Д',
    maximumSpeed: '200',
    transmission: 'Автомат',
    cityFuelConsumption: '7.5',
    highwayFuelConsumption: '5.1',
    fuelTankCapacity: '78',
    driveType: 'Передній',
    combinedFuelConsumption: '6.2',
    lengthMm: '4600',
    widthMm: '1875',
    heightMm: '1725',
    wheelbaseMm: '2730',
    curbWeightKg: '1620',
    grossWeightKg: '2120',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: true },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },
  {
    id: 9,
    carBrand: 'HAVAL',
    model: 'H9',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img5.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img1.jpg',
    ],
    bealerName: 'Богдан-Авто Запоріжжя',
    dealerSity: 'м. Запоріжжя',
    engine: '2.0 D',
    enginePowerHP: '150/3600',
    year: '2025',
    exteriorColor: 'White',
    regularPrice: '1 980 000',
    loanRepayment: '11500',
    specialOffer: true,
    pickUpOffer: false,
    availablCar: true,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    accel0to100: 'Н/Д',
    maximumSpeed: '200',
    transmission: 'Автомат',
    cityFuelConsumption: '7.5',
    highwayFuelConsumption: '5.1',
    fuelTankCapacity: '78',
    driveType: 'Передній',
    combinedFuelConsumption: '6.2',
    lengthMm: '4750',
    widthMm: '1920',
    heightMm: '1800',
    wheelbaseMm: '2800',
    curbWeightKg: '1850',
    grossWeightKg: '2500',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: true },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },
  {
    id: 10,
    carBrand: 'HAVAL',
    model: 'H6 GT',
    imgCar: 'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
    sliderImages: [
      'https://bogdanauto.com.ua/wp-content/uploads/2025/10/Frame-31945-3-2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img5.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img2.jpg',
      'https://bogdanauto.com.ua/wp-content/themes/bah-theme/images/h5/img1.jpg',
    ],
    bealerName: 'Богдан-Авто Чернівці',
    dealerSity: 'м. Чернівці',
    engine: '2.0 T',
    enginePowerHP: '150/3600',
    year: '2025',
    exteriorColor: 'Orange',
    regularPrice: '1 670 000',
    loanRepayment: '10100',
    specialOffer: true,
    pickUpOffer: true,
    availablCar: true,
    trimLevel: 'Standart',
    fuelType: 'Бензин',
    accel0to100: 'Н/Д',
    maximumSpeed: '200',
    transmission: 'Автомат',
    cityFuelConsumption: '7.5',
    highwayFuelConsumption: '5.1',
    fuelTankCapacity: '78',
    driveType: 'Повний',
    combinedFuelConsumption: '6.2',
    lengthMm: '4550',
    widthMm: '1850',
    heightMm: '1730',
    wheelbaseMm: '2720',
    curbWeightKg: '1600',
    grossWeightKg: '2100',
    specs: [
      {
        title: 'Безпека',
        items: [
          { label: 'Шторки безпеки по всій довжині', value: true },
          { label: 'ELK+SDF (Аварійне утримання в смузі руху)', value: true },
          { label: 'LSA (Моніторинг оточення)', value: false },
          { label: 'AEB (Екстрене гальмування)', value: true },
        ],
      },
      {
        title: 'Технології комфорту',
        items: [
          { label: 'Адаптивний круїз-контроль', value: true },
          { label: 'Клімат-контроль', value: true },
        ],
      },
      {
        title: 'Інтер’єр',
        items: [
          { label: 'Шкіряні сидіння', value: true },
          { label: 'Підігрів сидінь', value: true },
        ],
      },
    ],
  },
];
